default: &default
  runner:
    instances: 1
    input_queue: "svp_billing"
    output_queue: "svp_book_keeper"

default_database: &default_database
  adapter: postgresql
  encoding: utf8

default_rabbit: &default_rabbit
  port: 5672




development:
  <<: *default

  database:
    <<: *default_database

    host: localhost
    port: 5432
    database: svpdb1
    username: test_usr_dev1
    password: test_usr_dev1

  rabbit:
    <<: *default_rabbit
    host: 'localhost'  
    user: 'guest'
    password: 'guest'

  redis_alarm:
    host: localhost
    port: 6379
    db: "svp:alarm"

test:
  <<: *default

  database:
    <<: *default_database

  rabbit:
    <<: *default_rabbit


production:
  <<: *default

  database:
    <<: *default_database
    host: 172.17.10.24
    port: 5432
    database: svpdb
    username: svpdb
    password: qir29sir

    
  rabbit:
    <<: *default_rabbit
    host: '172.17.10.26'  
    user: 'svp_app'
    password: 'svp_app'

  redis_alarm:
    host: 172.17.10.21
    port: 6379
    db: "svp:alarm"