default: &default
  runner:
    instances: 1
    input_queue: "svp_billing"
    output_queue: "svp_book_keeper"

default_database: &default_database
  adapter: postgresql
  encoding: utf8

development:
  <<: *default

  database:
    <<: *default_database

    host: localhost
    port: 5432
    database: svpdb1
    username: test_usr_dev1
    password: test_usr_dev1

  

test:
  <<: *default

  database:
    <<: *default_database


production:
  <<: *default

  database:
    <<: *default_database